export default [
    {
        "Nama": "Ikan Tuna",
        "NamaLatin": "Thunnini",
        "Kota": "Bali",
        "Protein": 23.33,
        "Kalori": 144,
        "Lemak": 4.9,
        "Harga": 32.5,
        "Img": "https://cdn.idntimes.com/content-images/community/2019/03/ikan-tuna-337d58f37de71665001b5431308e58ae_600x400.jpg",
        "id": 1,
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Salmon",
        "NamaLatin": "Oncorhynchus nerka",
        "Kota": "Jakarta",
        "Protein": 19.93,
        "Kalori": 179,
        "Lemak": 10.43,
        "Harga": 100,
        "Img": "https://i0.wp.com/gerava.com/wp-content/uploads/2019/12/Gambar-ikan-salmon.jpg?fit=500%2C333&ssl=1",
        "id": "2",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Tongkol",
        "NamaLatin": "Euthynnus affinis",
        "Kota": "Surabaya",
        "Protein": 13.7,
        "Kalori": 100,
        "Lemak": 1.5,
        "Harga": 23,
        "Img": "https://1.bp.blogspot.com/-zEzDXtVewzw/Wvt7q7k0yRI/AAAAAAAABJs/XmYOmBMmyFcHFTxj9e0gdjeKetiLOdJNQCLcBGAs/w1200-h630-p-k-no-nu/tongkol.jpg",
        "id": "3",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Belanak",
        "NamaLatin": "Moolgarda seheli",
        "Kota": "Makassar",
        "Protein": 24.8,
        "Kalori": 150,
        "Lemak": 4.9,
        "Harga": 20,
        "Img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXJgBF0doPqQ3kolQiHhCz8nu2Z4ZJIpeEbmMdywgwokzAG43OuzgcYMCAWr7hLIjbQNQ&usqp=CAU",
        "id": "4",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Teri",
        "NamaLatin": "Engraulidae sp",
        "Kota": "Medan",
        "Protein": 26.89,
        "Kalori": 210,
        "Lemak": 9.7,
        "Harga": 35,
        "Img": "https://ragamikan.com/wp-content/uploads/2019/11/teri.jpg",
        "id": "5",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Kembung",
        "NamaLatin": "Restrelliger sp.",
        "Kota": "Jepara",
        "Protein": 21.3,
        "Kalori": 125,
        "Lemak": 3.4,
        "Harga": 30,
        "Img": "https://i0.wp.com/rimbakita.com/wp-content/uploads/2020/12/ikan-kembung-jantan.jpg",
        "id": "6",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Udang Windu",
        "NamaLatin": "Penaeus monodon",
        "Kota": "Demak",
        "Protein": 11.4,
        "Kalori": 56,
        "Lemak": 0.6,
        "Harga": 90,
        "Img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/CSIRO_ScienceImage_2992_The_Giant_Tiger_Prawn.jpg/1200px-CSIRO_ScienceImage_2992_The_Giant_Tiger_Prawn.jpg",
        "id": "7",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Cumi-Cumi",
        "NamaLatin": "Loligo sp.",
        "Kota": "Jakarta",
        "Protein": 16.1,
        "Kalori": 75,
        "Lemak": 0.7,
        "Harga": 70,
        "Img": "https://asset-a.grid.id//crop/0x0:0x0/700x465/photo/bobofoto/original/22069_5-fakta-cumi-cumi-hewan-yang-punya-8-lengan-dan-2-tentakel.jpg",
        "id": "8",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Cakalang",
        "NamaLatin": "Katsuwonus pelami",
        "Kota": "Manado",
        "Protein": 19.6,
        "Kalori": 107,
        "Lemak": 0.7,
        "Harga": 35,
        "Img": "https://arenahewan.com/wp-content/uploads/2019/05/Skipjack-1280x720.jpg",
        "id": "9",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Tenggiri",
        "NamaLatin": "Scomberomorini",
        "Kota": "Palembang",
        "Protein": 19.3,
        "Kalori": 139,
        "Lemak": 6.3,
        "Harga": 40,
        "Img": "https://cdn.statically.io/img/4.bp.blogspot.com/-838MBWESuLc/XAXTN-wcl2I/AAAAAAAAF7Y/_J4qPIBeRYcOX5gxlAl3icqPRPGPzWHLgCLcBGAs/s1600/1.jpg",
        "id": "10",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Kakap",
        "NamaLatin": "Lutjanidae sp",
        "Kota": "Tabanan",
        "Protein": 20,
        "Kalori": 100,
        "Lemak": 1.34,
        "Harga": 45,
        "Img": "https://asset.kompas.com/crops/v5x8yOzQa7KGeXiQ0-Gv9aSR-Is=/100x67:900x600/750x500/data/photo/2021/05/17/60a1f8649080d.jpg",
        "id": "11",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Kerapu",
        "NamaLatin": "Epinephelus sp",
        "Kota": "Tanjung pinang",
        "Protein": 19.38,
        "Kalori": 92,
        "Lemak": 1.02,
        "Harga": 35,
        "Img": "https://assets.petpintar.com/files/userfiles/2/1603098771-jenis-ikan-kerapu-6.jpg",
        "id": "12",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Baronang",
        "NamaLatin": "Siganus sp",
        "Kota": "Batam",
        "Protein": 14.5,
        "Kalori": 78,
        "Lemak": 0.6,
        "Harga": 45,
        "Img": "https://assets.pojoksatu.id/2020/07/Ikan-Baronang-390x250.jpg",
        "id": "13",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Lobster",
        "NamaLatin": "Nephropidae sp.",
        "Kota": "Balikpapan",
        "Protein": 27.55,
        "Kalori": 129,
        "Lemak": 1.25,
        "Harga": 380,
        "Img": "https://image-cdn.medkomtek.com/9CSXREBjZBjQ-gurRloJWK5QURI=/1200x675/smart/klikdokter-media-buckets/medias/2310216/original/025209600_1577372844-Heboh-Soal-Benih-Lobster-Ini-Manfaatnya-Bagi-Kesehatan-Anda-Shutterstock_22673587.jpg",
        "id": "14",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan barakuda",
        "NamaLatin": "Sphyraena sp.",
        "Kota": "Malang",
        "Protein": 94,
        "Kalori": 70,
        "Lemak": 60,
        "Harga": 40,
        "Img": "https://cdn.idntimes.com/content-images/community/2019/08/mexico-great-barracuda-bf32c34809ed740aa115ea958ed55ddc_600x400.jpg",
        "id": "15",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan  Blue Marlin",
        "NamaLatin": "Makaira nigricans",
        "Kota": "Jombang",
        "Protein": 26,
        "Kalori": 100,
        "Lemak": 0.4,
        "Harga": 40,
        "Img": "https://www.dictio.id/uploads/db3342/original/3X/7/c/7cf58fb848646a5a1b2440c9994d4428634a27ed.jpg",
        "id": "16",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan ayam-ayam",
        "NamaLatin": "Strary triggerfish",
        "Kota": "Karangasem",
        "Protein": 74,
        "Kalori": 50,
        "Lemak": 13,
        "Harga": 25,
        "Img": "https://1.bp.blogspot.com/-g8Ad3Cx29Bw/XVrkKu6TGQI/AAAAAAAADok/1-eYmP8smWYeeIw60G_C_YDyA-ZvHLS_wCLcBGAs/w1280-h720-p-k-no-nu/ikan%2Bayam%2Bayam%2Badalah.jpg",
        "id": "17",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan kuwe gerong",
        "NamaLatin": "Caranx ignobilis",
        "Kota": "Solo",
        "Protein": 74,
        "Kalori": 50,
        "Lemak": 13,
        "Harga": 25,
        "Img": "https://www.dictio.id/uploads/db3342/original/3X/1/1/115e7ea6313c61dcc279b8776c89300930a1e0ad.jpg",
        "id": "18",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan sarden ",
        "NamaLatin": "Sardina pilchardus",
        "Kota": "Semarang",
        "Protein": 24.62,
        "Kalori": 180,
        "Lemak": 11.45,
        "Harga": 42,
        "Img": "https://asset-a.grid.id/crop/0x0:0x0/x/photo/2020/02/17/2999385616.jpg",
        "id": "19",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Rajungan ",
        "NamaLatin": "Portunidae sp",
        "Kota": "Palu",
        "Protein": 19,
        "Kalori": 97,
        "Lemak": 1.5,
        "Harga": 90,
        "Img": "https://awsimages.detik.net.id/community/media/visual/2018/10/29/29ac6804-9123-458d-9448-186ebc6280a5.jpeg?a=1",
        "id": "20",
        "category": "Ikan Air Laut"
    },
    {
        "Nama": "Ikan Nila",
        "NamaLatin": "Oreochromis Niloticus",
        "Kota": "Salatiga",
        "Protein": 25,
        "Kalori": 128,
        "Lemak": 3,
        "Harga": 20,
        "Img": "https://assets.petpintar.com/cache/720/540/article/467/1622390139-ciri-ciri-ikan-nila-banner.jpg",
        "id": "21",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Bandeng",
        "NamaLatin": "Chanos chanos",
        "Kota": "Depok",
        "Protein": 20,
        "Kalori": 120,
        "Lemak": 2.8,
        "Harga": 18,
        "Img": "https://joss.co.id/data/uploads/2019/02/ikan-bandeng-punya-gizi.jpg",
        "id": "22",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Lele",
        "NamaLatin": "Clarias sp",
        "Kota": "Tangerang",
        "Protein": 15.5,
        "Kalori": 135,
        "Lemak": 7.6,
        "Harga": 15,
        "Img": "https://cdn1-production-images-kly.akamaized.net/H6VuMXcbh2pQCD55-MlykqXedwY=/640x640/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2750517/original/051457200_1552481948-foto_A.jpg",
        "id": "23",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Mas",
        "NamaLatin": "Cyprinus carpio",
        "Kota": "Cibubur",
        "Protein": 17.8,
        "Kalori": 127,
        "Lemak": 5.8,
        "Harga": 15,
        "Img": "https://image.cermati.com/q_70/aundqva6mspsrzyhr7tn",
        "id": "24",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Gurami",
        "NamaLatin": "Osphronemus goramy",
        "Kota": "Padang",
        "Protein": 18,
        "Kalori": 126,
        "Lemak": 5.6,
        "Harga": 22,
        "Img": "https://gdmagri.com/wp-content/uploads/2020/06/harga-gurame.jpg",
        "id": "25",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Patin",
        "NamaLatin": "Pangasius pangasius",
        "Kota": "Sumbawa",
        "Protein": 15,
        "Kalori": 132,
        "Lemak": 6,
        "Harga": 18.5,
        "Img": "https://cms.sehatq.com/cdn-cgi/image/f=auto,width=480,fit=pad,background=white,quality=100/public/img/article_img/5-alasan-mengapa-harus-hati-hati-sebelum-konsumsi-ikan-patin-siam-1601005168.jpg",
        "id": "26",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Mujaer",
        "NamaLatin": "Oreochromis mossambicus",
        "Kota": "Sabang",
        "Protein": 46.9,
        "Kalori": 416,
        "Lemak": 23.9,
        "Harga": 20,
        "Img": "https://asset-a.grid.id/crop/0x0:0x0/945x630/photo/2019/10/01/2867727064.jpeg",
        "id": "27",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan bawal",
        "NamaLatin": "Colossoma macropomum",
        "Kota": "Gresik",
        "Protein": 19,
        "Kalori": 96,
        "Lemak": 1.7,
        "Harga": 18,
        "Img": "https://asset.kompas.com/crops/Vum4EI4jb5m1b4qHTCtM1zOfz8c=/15x0:930x610/750x500/data/photo/2021/07/03/60dfe4e76d220.jpg",
        "id": "28",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Gabus",
        "NamaLatin": "Channa striata",
        "Kota": "Solo",
        "Protein": 16.2,
        "Kalori": 80,
        "Lemak": 0.5,
        "Harga": 50,
        "Img": "https://media.suara.com/pictures/970x544/2017/11/21/97366-ikan-gabus.jpg",
        "id": "29",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Belut",
        "NamaLatin": "Monopterus albus",
        "Kota": "Mojokerto",
        "Protein": 14.6,
        "Kalori": 70,
        "Lemak": 0.8,
        "Harga": 35,
        "Img": "https://images.tokopedia.net/img/cache/700/VqbcmM/2020/7/11/9331da34-e967-4ef1-ab70-8f55d3be4d13.jpg",
        "id": "30",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Dorang",
        "NamaLatin": "Pampus argenteus",
        "Kota": "Madiun",
        "Protein": 17.21,
        "Kalori": 84,
        "Lemak": 1.22,
        "Harga": 30,
        "Img": "https://cf.shopee.co.id/file/929055d7b5830ad4cf23a58d6afaa205",
        "id": "31",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Sidat",
        "NamaLatin": "Anguilla sp",
        "Kota": "Banyuwangi",
        "Protein": 80,
        "Kalori": 187,
        "Lemak": 12,
        "Harga": 35,
        "Img": "https://cdn.idntimes.com/content-images/community/2019/08/cov-foodtribute-4805c6311f84975641d8e6c6fed44c49_600x400.jpg",
        "id": "32",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Tawes",
        "NamaLatin": "Barbonymus gonionotus",
        "Kota": "Bandung",
        "Protein": 42,
        "Kalori": 193,
        "Lemak": 1.5,
        "Harga": 2.5,
        "Img": "https://cdn.statically.io/img/3.bp.blogspot.com/-QIgcZ7K-sU4/XCHN03j4UGI/AAAAAAAAGjQ/Lmq-K-j5qQgIR-aSasCnx01eQ9bND4pfwCLcBGAs/s1600/ikan%2Btawes%2B1.jpg",
        "id": "33",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Betutu",
        "NamaLatin": "Oxyeleotris marmorata ",
        "Kota": "Tabanan",
        "Protein": 16.2,
        "Kalori": 80,
        "Lemak": 0.5,
        "Harga": 75,
        "Img": "https://static.wixstatic.com/media/bcf5ea_429c2d6f86554fe9bcce23ad262b4dd7~mv2.jpg/v1/fill/w_658,h_300,al_c,q_90/bcf5ea_429c2d6f86554fe9bcce23ad262b4dd7~mv2.jpg",
        "id": "34",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Lundu",
        "NamaLatin": "Mystus sp",
        "Kota": "Pontianak",
        "Protein": 26,
        "Kalori": 128,
        "Lemak": 3,
        "Harga": 8,
        "Img": "https://panennews.com/wp-content/uploads/2020/04/Ikan-Lundu-Keting.jpg",
        "id": "35",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Wader",
        "NamaLatin": "Barbodes binotatus",
        "Kota": "Manado",
        "Protein": 14.88,
        "Kalori": 84,
        "Lemak": 2.27,
        "Harga": 34,
        "Img": "https://indonesia.go.id/assets/upload/headline//1564027918_Ikan_wader.jpg",
        "id": "36",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Jelawat",
        "NamaLatin": "Leptobarbus hoevenii",
        "Kota": "Kupang",
        "Protein": 17.8,
        "Kalori": 80,
        "Lemak": 0.9,
        "Harga": 50,
        "Img": "https://memancing.info/wp-content/uploads/2021/06/images-4-1.jpeg",
        "id": "37",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Nilem",
        "NamaLatin": "Osteochilus vittatus",
        "Kota": "Merauke",
        "Protein": 17.76,
        "Kalori": 84,
        "Lemak": 0.92,
        "Harga": 9,
        "Img": "https://i0.wp.com/fredikurniawan.com/wp-content/uploads/2018/03/1-7.jpg",
        "id": "38",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Biawan",
        "NamaLatin": "Helostoma temminckii",
        "Kota": "Bali",
        "Protein": 14.9,
        "Kalori": 90,
        "Lemak": 2.5,
        "Harga": 60,
        "Img": "https://nilaigizi.com/assets/images/produk/produk_1535461080.jpg",
        "id": "39",
        "category": "Ikan Air Tawar"
    },
    {
        "Nama": "Ikan Hampala",
        "NamaLatin": "Hampala macrolepidota",
        "Kota": "Jember",
        "Protein": 17,
        "Kalori": 80,
        "Lemak": 1,
        "Harga": 95,
        "Img": "https://upload.wikimedia.org/wikipedia/commons/6/64/Hampal_macrol_101016-7858_mp.JPG",
        "id": "40",
        "category": "Ikan Air Tawar"
    }
];